version: '3.8'

services:
  ansible:
    image: willhallonline/ansible:latest
    container_name: ansible-control
    working_dir: /ansible
    volumes:
      - .:/ansible
      - C:/newssh:/root/.ssh
    stdin_open: true
    tty: true
    command: sh